language: python
sudo: false

branches:
   only:
     - master

python:
  - 3.6
  - 2.7
  - 3.5

install:
  - pip install flake8
  - pip install . pytest-flake8 flake8-docstrings flake8-import-order

script:
  - pytest --flake8
